services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    expose:
     - "9000"
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
       condition: service_started
    restart: always
    healthcheck:
     test: ["CMD", "php-fpm81", "-t"]
     interval: 10s
     timeout: 5s
     retries: 3

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    restart: always

  adminer:
   build:
    context: ./requirements/bonus/adminer
   container_name: adminer
   depends_on:
    mariadb:
     condition: service_healthy
   ports:
     - "8080:8080"
   networks:
     - inception
   restart: always

  redis:
   build:
    context: ./requirements/bonus/redis
   container_name: redis
   networks:
    - inception
   restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/agraille/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/agraille/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
