#!/bin/bash

INIT_SQL_FILE="/docker-entrypoint-initdb.d/init.sql"

MYSQL_USER_PASSWORD=$(cat /run/secrets/mysql_user_password)
MYSQL_ROOT_PASSWORD=$(cat /run/secrets/mysql_root_password)

cat << EOF > ${INIT_SQL_FILE}
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_USER_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'localhost';
ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
USE ${MYSQL_DATABASE};
FLUSH PRIVILEGES;
EOF


chmod 644 ${INIT_SQL_FILE}
echo "Script SQL d'initialisation généré avec succès dans ${INIT_SQL_FILE}"
